### ISSUE TITLE
server.js stop at first request

### ISSUE THREAD

**Issue by sebmoule** [ManoMarks/docker-swarm-visualizer#12]
I have try to send requests on the app but it fails with this error :  

```
`[cloud@bastion]$ docker pull manomarks/visualizer
Using default tag: latest
slave2: Pulling manomarks/visualizer:latest... : downloaded 
slave1: Pulling manomarks/visualizer:latest... : downloaded 
master1: Pulling manomarks/visualizer:latest... : downloaded 
[cloud@bastion]$ docker-compose up
Starting dockerswarmvisualizer_visu_1
Attaching to dockerswarmvisualizer_visu_1
visu_1  | npm info it worked if it ends with ok
visu_1  | npm info using npm@2.14.4
visu_1  | npm info using node@v4.1.2
visu_1  | npm info prestart swarmVisualizer@0.0.1
visu_1  | npm info start swarmVisualizer@0.0.1
visu_1  | 
visu_1  | > swarmVisualizer@0.0.1 start /app
visu_1  | > node server.js
visu_1  | 
visu_1  | undefined
visu_1  | undefined:1
visu_1  | 404 page not found
visu_1  |     ^
visu_1  | 
visu_1  | SyntaxError: Unexpected token p
visu_1  |     at Object.parse (native)
visu_1  |     at IncomingMessage.<anonymous> (/app/server.js:68:36)
visu_1  |     at emitNone (events.js:72:20)
visu_1  |     at IncomingMessage.emit (events.js:166:7)
visu_1  |     at endReadableNT (_stream_readable.js:893:12)
visu_1  |     at doNTCallback2 (node.js:430:9)
visu_1  |     at process._tickCallback (node.js:344:17)
visu_1  | 
visu_1  | npm info swarmVisualizer@0.0.1 Failed to exec start script
visu_1  | npm ERR! Linux 4.4.0-28-generic
visu_1  | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
visu_1  | npm ERR! node v4.1.2
visu_1  | npm ERR! npm  v2.14.4
visu_1  | npm ERR! code ELIFECYCLE
visu_1  | npm ERR! swarmVisualizer@0.0.1 start: `node server.js`
visu_1  | npm ERR! Exit status 1
visu_1  | npm ERR! 
visu_1  | npm ERR! Failed at the swarmVisualizer@0.0.1 start script 'node server.js'.
visu_1  | npm ERR! This is most likely a problem with the swarmVisualizer package,
visu_1  | npm ERR! not with npm itself.
visu_1  | npm ERR! Tell the author that this fails on your system:
visu_1  | npm ERR!     node server.js
visu_1  | npm ERR! You can get their info via:
visu_1  | npm ERR!     npm owner ls swarmVisualizer
visu_1  | npm ERR! There is likely additional logging output above.
visu_1  | 
visu_1  | npm ERR! Please include the following file with any support request:
visu_1  | npm ERR!     /app/npm-debug.log
```
also can we call it in HTTPS ?

Thanks

**Comment by ManoMarks** [comment]
Do you have a Swarm running? Are you running Docker 1.12? It looks like you're not getting anything back from the Docker Remote API. Are you running this on Windows, Mac, or Linux?

**Comment by sebmoule** [comment]
I am running docker 1.11 it's not compatible ?

Sébastien

**Comment by ManoMarks** [comment]
Correct
